### ISSUE TITLE
Service/Model layer: Add Participation from students to quiz

### ISSUE THREAD

**Issue by ChristofferGamel** [AAU-P5-Moodle/moodle-1#55]
In the livequiz_services.php:
https://github.com/AAU-P5-Moodle/moodle-1/blob/staging/server/moodle/mod/livequiz/classes/services/livequiz_services.php

You'll need to add a service method for appending a student to the quiz

This method is to be called from the frontend, in order to seperate model logic from the frontend
The method should be called with the corresponding studentid and quizid

This service method's responsibility is to perform logic operations on the model

For the model, i would recommend following a similar pattern as the questions_answers_relation.php:
https://github.com/AAU-P5-Moodle/moodle-1/blob/staging/server/moodle/mod/livequiz/classes/models/questions_answers_relation.php

This class should be responsible for receiving data and appending it to the corresponding database table

If you have any questions, feel free to reach out, and i will give you a rundown of my thoughts behind the implementation

DOD
This task is considered done, when the frontend is able to call the service layer method, allowing for storing a participation from a student, in the 'participates' table. The model and service layer should also have methods relevant for retrieving this data

**Comment by adomasciplys** [comment]
As for now there is no way to mark a participation as finished. Hence, every time you enter a new quiz, a new participation is created in the DB. It could be an idea to have a "finished" attribute in the participation table in order to mark if this participation is done.
